### ISSUE TITLE
buckaroo resolve -> Could not read project manifest

### ISSUE THREAD

**Issue by zfedoran** [njlr/buckaroo-test-glfw-glfw#1]
Perhaps I'm not sure what I'm doing, but the instructions don't seem to work for me. I'm getting similar results for the `sfml` test project as well...

```
😭 06:53 pm:buckaroo-test-glfw-glfw $ buckaroo install
System.Exception: No lock file was found. Perhaps you need to run 'buckaroo resolve'?
   at Buckaroo.Tasks.readLock@88.Invoke(Unit unitVar) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/Tasks.fs:line 97
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Buckaroo.Tasks.getContext@59-12.Invoke(AsyncActivation`1 ctxt) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/Tasks.fs:line 59
   at Buckaroo.Tasks.getContext@42-9.Invoke(AsyncActivation`1 ctxt) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/Tasks.fs:line 42
   at Buckaroo.Bash.runBashSync@71-7.Invoke(AsyncActivation`1 ctxt) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/Bash.fs:line 71
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@607.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
info Installing packages...
```

Followed by

```
😭 06:53 pm:buckaroo-test-glfw-glfw $ buckaroo resolve
System.Exception: Could not read project manifest. Are you sure you are in the right directory?  ---> System.IO.FileNotFoundException: Could not find file '/tmp/buckaroo-test-glfw-glfw/buckaroo.toml'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at Buckaroo.Files.readFile@45.Invoke(Unit unitVar) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/Files.fs:line 45
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Buckaroo.Tasks.readLockIfPresent@106-4.Invoke(AsyncActivation`1 ctxt) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/Tasks.fs:line 106
   at Buckaroo.Tasks.getContext@59-12.Invoke(AsyncActivation`1 ctxt) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/Tasks.fs:line 59
   at Buckaroo.Tasks.getContext@42-9.Invoke(AsyncActivation`1 ctxt) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/Tasks.fs:line 42
   at Buckaroo.Bash.runBashSync@71-7.Invoke(AsyncActivation`1 ctxt) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/Bash.fs:line 71
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@607.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   --- End of inner exception stack trace ---
   at Buckaroo.Tasks.catchHandler@1-4(Exception _arg2) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/Tasks.fs:line 77
   at Buckaroo.Tasks.readManifest@68-7.Invoke(Exception edi) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/Tasks.fs:line 68
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt, FSharpFunc`2 catchFilter, ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
```

Please let me know what I might be doing wrong.

**Comment by njlr** [comment]
> Could not find file '/tmp/buckaroo-test-glfw-glfw/buckaroo.toml'.

Is there a `buckaroo.toml` file in the directory where you run `buckaroo resolve`?

Please can you link to the repo also?

**Comment by njlr** [comment]
My mistake, though this issue was on the main repo. 2 secs...

**Comment by njlr** [comment]
I have updated this sample to the latest Buckaroo (`2.2.0`). Hopefully it works now!

**Comment by zfedoran** [comment]
Thanks @njlr! 

That does help, I am able to get a bit further now. I guess the same issue exists on the [sfml test](https://github.com/njlr/buckaroo-test-sfml-sfml) repo.

For glfw, I think I may be missing some more dependencies, perhaps related to [glad](https://github.com/LoopPerfect/buckaroo/issues/344).

```
😭 11:42 am:buckaroo-test-glfw-glfw $ buck run :boing
Not using buckd because watchman isn't installed.
Using additional configuration options from .buckconfig.d/.buckconfig.buckaroo
In file included from deps/glad.c:26:
deps/glad/glad.h:87:10: fatal error: 'KHR/khrplatform.h' file not found
#include <KHR/khrplatform.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
Parsing buck files: finished in 2.1 sec
Building: finished in 1.5 sec (100%) 18/39 jobs, 18 updated
  Total time: 4.2 sec
Command failed with exit code 1.
stderr: In file included from deps/glad.c:26:
deps/glad/glad.h:87:10: fatal error: 'KHR/khrplatform.h' file not found
#include <KHR/khrplatform.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
    When running <c preprocess_and_compile>.
    When building rule buckaroo.github.buckaroo-pm.glfw//deps:glad#compile-glad.c.o506cccc8,macosx-x86_64.
```

**Comment by njlr** [comment]
What platform are you on? I only tested on Ubuntu x64

**Comment by zfedoran** [comment]
@njlr Mac OSX version `10.14.5 (18F132)` Mojave.
